### ISSUE TITLE
Fungsi Database tbl_token_pelanggan

### ISSUE THREAD

**Issue by valda96** [bahyusanciko/Tiket-Bus#11]
Gan untuk tabel yang ini dibagaimanakan untuk verifikasi email user? Terima Kasih
![image](https://user-images.githubusercontent.com/61334303/100040564-1e85d400-2e3a-11eb-8b79-58377f3aed3f.png)

**Comment by bahyusanciko** [comment]
ya bisa , harus send mail untuk verfikasi masukin email dulu ya di fungsi send mail di setiap controller yang ngerim email
