### ISSUE TITLE
Error QrCode

### ISSUE THREAD

**Issue by ivanvino247** [bahyusanciko/Tiket-Bus#13]
Error waktu sehabis klik Proses Tiket (php : versi 8._)

![Screenshot (848)](https://user-images.githubusercontent.com/80973694/111877790-8a86dc00-89d7-11eb-95da-54ffcc71d1af.png)

**Comment by bahyusanciko** [comment]
Ok noted baru bro nanti gw check , bdw pake versi berapa phpnya

**Comment by bahyusanciko** [comment]
Jgn pake php 8 minimal 7 keatas ya
