### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RifkyChandrra** [bahyusanciko/Tiket-Bus#25]
Pas buka dilokalhost
localhost/ci-tiket
error kaya gini
An uncaught Exception was encountered
Type: Error

Message: Class "Dotenv\Dotenv" not found

Filename: C:\xampp\htdocs\ci-tiket\application\config\hooks.php

Line Number: 7

Backtrace:

File: C:\xampp\htdocs\ci-tiket\index.php
Line: 315
Function: require_once

**Comment by DPRRI** [comment]
[Disini solusinya](https://stackoverflow.com/questions/37199237/fatal-error-class-dotenv-dotenv-not-found-in)

**Comment by bahyusanciko** [comment]
install composer bro
