### ISSUE TITLE
ini pesan errornya gan.

### ISSUE THREAD

**Issue by alwinfau** [bahyusanciko/Tiket-Bus#7]
![Capture](https://user-images.githubusercontent.com/41532535/89288156-614f5080-d67f-11ea-9cdf-f215f6ae0e0d.PNG)
![02](https://user-images.githubusercontent.com/41532535/89288160-63191400-d67f-11ea-9a81-6da69658a51c.PNG)

**Comment by alwinfau** [comment]
ini untuk login front endnya apa gan. ngk bisa login juga

![03](https://user-images.githubusercontent.com/41532535/89288263-8ba10e00-d67f-11ea-9786-79186851330c.PNG)

**Comment by alwinfau** [comment]
untuk profile user tidak bisa upadate gan

![04](https://user-images.githubusercontent.com/41532535/89288421-d458c700-d67f-11ea-9599-67ac803412c8.PNG)

**Comment by alwinfau** [comment]
Ini untuk kirim R-Tiketnya ke email tadi gan tidak bisa juga

![05](https://user-images.githubusercontent.com/41532535/89288596-1c77e980-d680-11ea-9c7e-460dfb066627.PNG)

**Comment by bahyusanciko** [comment]
oke untuk send email rubah code fungsi send email sesuai email yg mau di jadiin send email bro, untuk untuk login users pelanggan check kembali errornya apa bro dan fungsi update profile di dashbaord emg blm ya dan untuk bikin tujuan hanya tidak bisa edit ya
